/**
 * All Action types will listed here
 */

// Auth Actions
export const DO_SIGNIN_REQUEST = 'DO_SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const RESET_AUTH_SCREEN_DATA = 'RESET_AUTH_SCREEN_DATA';

export const DO_SIGNUP_REQUEST = 'DO_SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//EVENT ACTIONS
export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS';
export const GET_REPO_FAILURE = 'GET_REPO_FAILURE';
export const GET_REPO_REQUEST = 'GET_REPO_REQUEST';

export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAILURE = 'GET_ISSUES_FAILURE';
export const GET_ISSUES_REQUEST = 'GET_ISSUES_REQUEST';

export const GET_PR_SUCCESS = 'GET_PR_SUCCESS';
export const GET_PR_FAILURE = 'GET_PR_FAILURE';
export const GET_PR_REQUEST = 'GET_PR_REQUEST';

export const SUBSCRIPTION_FAILURE = 'SUBSCRIPTION_FAILURE';
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_REQUEST = 'SUBSCRIPTION_REQUEST';

export const CREATE_ISSUE_FAILURE = 'CREATE_ISSUE_FAILURE';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';

export const ADD_SUBSCRIBED_REPO_REQUEST = 'ADD_SUBSCRIBED_REPO_REQUEST';
export const REMOVE_SUBSCRIBED_REPO_REQUEST = 'REMOVE_SUBSCRIBED_REPO_REQUEST';

//COMMON ACTIONS
export const STOP_LOADING_SUCCESS = 'STOP_LOADING_SUCCESS';
export const START_LOADING_SUCCESS = 'START_LOADING_SUCCESS';

